### PR TITLE
Ship CHANGELOG.md with debian.

### PR DESCRIPTION
**Pull request by disco-stu**
Ship CHANGELOG.md as part of the debian packge. The debian changelog
mentioned already.

### CODE REVIEW

**Comment by ioguix** [comment]
Thank you Adrian!

**Comment by disco-stu** [comment]
I'm sorry. I've made a mistake. The upstream changelog is already shipped with the deb package. /usr/share/doc/resource-agents-paf/changelog.gz. I've searched for a file named CHANGELOG.md* and didn't found one.

Sorry for the noise and trouble.

**Comment by ioguix** [comment]
Argh, indeed. I didn't noticed either...

As the 2.2.0-2 did not hit the pgdg repo, I think I'll just revert the commits (yours and mine) and remove the 2.2.0-2 from github. It shouldn't hurt anyone I suppose...

Thoughts?

**Comment by disco-stu** [comment]
Works for me.

**Comment by ioguix** [comment]
mh, too late, it seems the package has been pushed to the Debian's FTP.

I'll remove it without publishing a new debian version.

**Pull request merged**
