### PR TITLE
Debian fixes

### PR DESCRIPTION
**Pull request by disco-stu**
Hi,

regarding your mail on the pgsql-pkg-debian list I had a look at the debian package. I've noticed a few discrepancies. Two lintian warnings and a missing watch file. See the commit messages or the d/changelog for more information.

Regards,
 - Adrian

### CODE REVIEW

**Comment by ioguix** [comment]
Hi,

I merged an update to the control file some minutes before your PR conflicting with it. I fixed everything, but I have a little doubt about the dependencies in the control file:
* how should I handle the perl dependency? 
* now I tried to fix the conflict, does the current control file is OK according to you?


Thank you for your patches!

**Comment by disco-stu** [comment]
I wouldn't add pacemaker nor corosync to the dependencies. Example: what if someone don't want to run the hole pacemaker/corosync stack but run the lightweight pacemaker-remote service instead. Or what if someone would like to run a pacemaker/heartbeat setup instead of pacemaker/corosync?

I think you're concerned about the version dependency to 1.1.13 or above. I don't know if that's a real problem. In debian the the only distribution that ships pacemaker < 1.1.13 is wheezy. If you want to make sure the right version of pacemaker{,-remote} is install than add "pacemaker (>=1.1.13) | pacemaker-remote (>=1.1.13)" as dependency.

**Comment by ioguix** [comment]
Indeed, I'm concerned about the Pacemaker 1.1.13 and corosync 2.x, because the RA is using `attrd_updater --private` which is not compatible with other stacks/versions.

Version 1.x of paf doesn't use it though, that's why it is compatible with corosync 1.x and pacemaker before 1.1.13.

**Comment by disco-stu** [comment]
I think the best way to ensure the right pacemaker version is to depend on "pacemaker (>=1.1.13) | pacemaker-remote (>=1.1.13)". Should I update the PR?

BTW: I've updated the watch file (~ vs _) and removed the empty line in d/changelog.

**Comment by ioguix** [comment]
Yes you are right.

I'm away from keyboard right now, I'll take care of this later or tomorrow unless you are faster than me.

Thank you for your help on this!

**Comment by ioguix** [comment]
Thanks again!

**Pull request merged**
